version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: sendo-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-sendo}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sendo-network
    restart: always

networks:
  sendo-network:
    driver: bridge

volumes:
  postgres-data: